In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [27]:
X=df.iloc[:,3:13].values
y=df.iloc[:,13].values

In [28]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [29]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [32]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X[:,1]=le1.fit_transform(X[:,1])
le2=LabelEncoder()
X[:,2]=le2.fit_transform(X[:,2])

In [33]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [34]:
#one hot encoding
from sklearn.preprocessing  import OneHotEncoder
one=OneHotEncoder(categorical_features=[1])
X=one.fit_transform(X).toarray()
X=X[:,1:]

In [36]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [64]:
#splitting the dataset
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [65]:
X_train

array([[0.0000000e+00, 1.0000000e+00, 6.6700000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.6383064e+05],
       [1.0000000e+00, 0.0000000e+00, 4.2700000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 5.7098000e+04],
       [0.0000000e+00, 0.0000000e+00, 5.3500000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8563076e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.3800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 5.9000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 6.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [66]:
X_test

array([[1.0000000e+00, 0.0000000e+00, 5.9700000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.9285267e+05],
       [0.0000000e+00, 0.0000000e+00, 5.2300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.2870210e+05],
       [0.0000000e+00, 1.0000000e+00, 7.0600000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 7.5732250e+04],
       ...,
       [0.0000000e+00, 1.0000000e+00, 5.7800000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.4153319e+05],
       [1.0000000e+00, 0.0000000e+00, 6.5000000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.1276480e+04],
       [1.0000000e+00, 0.0000000e+00, 5.7300000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.9295060e+05]])

In [67]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [68]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [69]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [70]:
#importing the keras
import keras

In [71]:
from keras.models import Sequential
from keras.layers import Dense

In [75]:
#initilizing the Ann
classifier=Sequential()


In [80]:
#adding the input layer and the first hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation="relu",input_dim=11))

C:\Users\vishal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [81]:
#Adding the second hidden layer
classifier.add(Dense(output_dim=6,init="uniform",activation="relu"))

C:\Users\vishal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [84]:
#adding the output layer
classifier.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))

C:\Users\vishal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [87]:
#compling the Ann
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [88]:
#fitting the ann to the training set
classifier.fit(X_train,y_train,batch_size=10,nb_epoch=100)

C:\Users\vishal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.6149 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.5344 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.5122 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.5071 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.5061 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.5060 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.5059 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.5060 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.5060 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.5059 - acc: 0.7960

8000/8000 [==============================] - 1s 122us/step - loss: 0.5059 - acc: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.5059 - acc: 0.7960
Epoch 84/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.5060 - acc: 0.7960
Epoch 85/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.5059 - acc: 0.7960
Epoch 86/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.5059 - acc: 0.7960
Epoch 87/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.5060 - acc: 0.7960
Epoch 88/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.5060 - acc: 0.7960
Epoch 89/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.5059 - acc: 0.7960
Epoch 90/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.5059 - acc: 0.7960
Epoch 91/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.5060 - acc: 0.7960
Epo

In [90]:
#predict
y_pred=classifier.predict(X_test)


In [92]:
y_pred

array([[0.2041851],
       [0.2041851],
       [0.2041851],
       ...,
       [0.2041851],
       [0.2041851],
       [0.2041851]], dtype=float32)

In [94]:
y_pred=(y_pred>0.5)

In [98]:
y_pred[:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])